theme: jekyll-theme-slate
title: (o(m)7-beta)
description: Next-generation visual programming environment for computer-aided music compositon

zip_url: "https://github.com/openmusic-project/om7/releases"

show_downloads: true

site.github.owner_url: https://github.com/j-bresson
site.github.owner_name: j-bresson